### ISSUE TITLE
[ - /roam2github-actions] Run failed: Roam Research backup - main ( - )

### ISSUE THREAD

**Issue by jeffrappaport** [everruler12/roam2github#15]
Hi Eric, my backup run started failing around 8 hours ago for no apparent reason.  I am not aware of any changes that might have led to this.  Any ideas about how to troubleshoot?  I have it set to run every 30 mins.  Thanks in advance 

![image](https://user-images.githubusercontent.com/70044805/118689741-2f494e00-b7bc-11eb-93dd-29fe152c49f0.png)

**Comment by everruler12** [comment]
Hi Jeff,
I took a look at your [logs](https://github.com/jeffrappaport/roam2github-actions/actions), and it looks like the backup did not even start, with a `This check was cancelled` message. I've never seen that before. Since its a public repo, there should not be an issue with action minutes (which you can check under Account Settings > Billing). If this was happening to me, I would try setting up a new actions repo to run the backups.
